### ISSUE TITLE
Sales Channel App Bridge Error`

### ISSUE THREAD

**Issue by Tom-Caz** [kinngh/shopify-nextjs-prisma-app#23]
Hello,

Whenever I switch my app to a sales channel, I get this error:

<img width="971" alt="Screenshot 2023-06-04 at 11 36 46 AM" src="https://github.com/kinngh/shopify-nextjs-prisma-app/assets/84303919/6f2e430a-9790-431b-8202-3a1b476a9c80">

This only occurs when my app is a sales channel. Everything seems to still be working properly, other than getting this popup.

Have any ideas on how to solve this?

Thanks.

**Comment by kinngh** [comment]
I haven't messed around with it being a sales channel, let me try this up when I can and push an update^  Thank you for flagging this!

**Comment by Tom-Caz** [comment]
Thank you! I appreciate it!

**Comment by kinngh** [comment]
The error is because of `<NavigationMenu />` component `/pages/_app.js`. Once that component is removed, it's working as expected. To confirm this is the error, add in this snippet to your `/pages/index.jsx` file:

```javascript
const app = useAppBridge();

app.error((data) => {
    console.dir(data, { depth: null });
  });
```

this will output an error with the navigation component, and I suspect this is something that's not allowed when creating a Sales Channel. Have to do more research on this, but I'll take a look at this a little later this week once I have some time.

**Comment by Tom-Caz** [comment]
Hello, just following up. Do you plan on adding Sales Channel support?

Thanks!

**Comment by kinngh** [comment]
...what's there to add support on this? I clearly replied to you on how to fix it and there's no need to follow up on this unless there's something else that's missing.

**Comment by Tom-Caz** [comment]
Sorry, I was unclear. Sales Channels have a bit different requirements than normal apps when it come to the App Bridge, so I was just curious if you would be adding an option in the template for Sales Channels.

I have fixed the bug based on what you sent, I should have posted the previous comment in discussions.

**Comment by kinngh** [comment]
No worries! What is AppBridge missing out on when it comes to converting this into a Sales Channel?
