### ISSUE TITLE
Where is the TypeScript version

### ISSUE THREAD

**Issue by infcodey** [kinngh/shopify-nextjs-prisma-app#24]
Hi,

In your video, you mentioned a typescript version. Do you mind letting me know where it is? Couldn't find it.

**Comment by kinngh** [comment]
The TypeScript version was pulled back since everyone wanted their own configuration and the whole idea of "This is just a starter and you're going to put in a little effort to add your packages" was too much for most devs and they decided to follow a life of crime and being rude instead, and I don't want that kinda energy.
