### ISSUE TITLE
Issue with the scope variable

### ISSUE THREAD

**Issue by PJijin** [kinngh/shopify-nextjs-prisma-app#29]
Will SHOPIFY_API_SCOPES work if we specify it as 'read_product, write_product' ? I'm having some issues at my end. 

After reading the @shopify/shopify-api documentation. It expects a string array as the scope. ['read_product','write_product'] 

https://github.com/kinngh/shopify-nextjs-prisma-app/blob/main/utils/shopify.js#L11

I think this line needs to be updated as

```
scopes: process.env.SHOPIFY_API_SCOPES ? process.env.SHOPIFY_API_SCOPES.split(',') : null
```

**Comment by kinngh** [comment]
There's no update that's necessary. In your `.env`, if you add in "read_product,write_product" as part of your scopes, it works just fine. Also, checking for the value doesn't make sense because you need to request at least one scope for the Shopify app to allow an installation. If you have `null` in your scopes, Shopify simply won't let you install the app since what are you building anyways that doesn't require you to interact with the Shopify's APIs.

I believe the issue is that you're adding your scopes in the `.env` file as `["read_product", "write_product"]` when it expects a string in your `env`, as `read_product,write_product` instead. Shopify does expect it to be an array of strings which is what we do with the `.split()`.

Also, just a heads up, it's much more useful information to me if you specify what exact issues you have so they can be debugged. As of right now I can't say a single thing about the array of issues you could potentially be facing since you're trying to recommend me a solution to a problem I don't know about instead of a problem and then a possible solution that would ease up my workflow.

**Comment by kinngh** [comment]
1. There's no update that's necessary
2. The API scopes are `read_products` and `write_products`, with an s. Read the documentation [here](https://shopify.dev/docs/api/usage/access-scopes)
