### ISSUE TITLE
OAuth Error | Cookie Not found

### ISSUE THREAD

**Issue by Hamzakdev112** [kinngh/shopify-nextjs-prisma-app#31]
Hey Harshdeep. i am facing an error while going through auth. Everything seems to work fine on first install but as soon as the token expires or I delete sessions and store from DB. I am getting an error. It seems that we are not able to accept the cookie "shopify_app_state" which is causing the OAuth to fail. I have noticed that this is a common issue and other people are facing it too but couldn't find a solution.

**Comment by kinngh** [comment]
See if this [gist](https://gist.github.com/kinngh/ab36102f4c1f2bdd9a56729253af222b) solves your problem.

**Comment by Hamzakdev112** [comment]
Yeah, it works. But not sure if it's a tangible solution but I guess this is the only possible way right now.

**Comment by kinngh** [comment]
...what about this isn't `tangible`?

**Comment by Hamzakdev112** [comment]
Not trying to put down anyone, it's a great repo, but if it's from Shopify's end, they should've sorted it out by now. But anyways, thanks a lot for providing me with the solution.

**Comment by kinngh** [comment]
I've never, in all these 6 years and 250+ apps, ran into a single instance of this error. It mostly comes down to the custom domain setup, or if you're trying to run auth between 2 deployments, that's where the issue happens.

The cookies work just fine - this actually opens up the entire thing to be used by any domain, making it a little less secure but works with any setup now. So it eventually comes down to how much you're putting attention to your setup and security, instead of just slapping on a bunch of code and pushing it up.
