### ISSUE TITLE
Any plans for Typescript version?

### ISSUE THREAD

**Issue by muchisx** [kinngh/shopify-nextjs-prisma-app#37]
Basically the title

**Comment by kinngh** [comment]
I have a love hate relationship with TypeScript. I know the benefits it brings and let's not get into that discussion, but here's the summary:
1. https://github.com/kinngh/shopify-nextjs-prisma-app-typescript
2. It's archived because I couldn't be bothered to accommodate everyone's request on "Oh you should be using this in this way", making my life more difficult
3. Using that as a guide and this being most up to date version, it's straight forward to transpile this into TypeScript
4. TS is not something I use in prod. I've been using JS + JSDocs for quite some time and only do TS when I'm contracted for a project that requires me to use TS. The reason why my repos get updated super regularly is purely because I use them everyday. I did try maintaining a TS version, but the lack of use and `I will unalive you` remarks on Twitter and other places reminded me how much I genuinely hate the TS community on socials, leading to no TS version of it

Though if you did decide to fork and build a TS version, please feel free to ping me and I'll help you in any way I can!

**Comment by muchisx** [comment]
@kinngh oh haha, I don't really mind much about other "mighty devs" think haha. But yeah if I end up using your repo I might turn it into TS and talk to you ! cheers man

**Comment by kinngh** [comment]
@muchisx oh please go ahead and do it! The repo from point 1 is still up so you should have a head start, first get it up to speed with this repo and then start doing generics and type mapping - you'll also end up learning the whole repo properly haha! But ye just ping me on Twitter if you need help with this!
